apiVersion: osrm.itayankri/v1alpha1
kind: OSRMCluster
metadata:
  name: single-profile-example
spec:
  pbfUrl: https://download.geofabrik.de/asia/israel-and-palestine-latest.osm.pbf
  profiles:
  - name: foot
    endpointName: foot
    minReplicas: 1
    maxReplicas: 4
  service:
    exposingServices: ["route", "table", "match"]
  persistence:
    storage: "100Mi"
    storageClassName: standard