apiVersion: osrm.itayankri/v1alpha1
kind: OSRMCluster
metadata:
  name: single-profile-example
spec:
  pbfUrl: https://download.geofabrik.de/australia-oceania/marshall-islands-latest.osm.pbf
  profiles:
  - name: foot
    endpointName: foot
    minReplicas: 1
    maxReplicas: 4
    speedUpdates:
      url: https://storage.cloud.google.com/revel_eta_prediction/hourly_speed_data
      schedule: "*/3 * * * *"
  service:
    exposingServices: ["route", "table", "match"]
  persistence:
    storage: "1000Mi"
    storageClassName: standard